"""Add selected_text to nodes

Revision ID: e08318967186
Revises: d9cdd04d1bac
Create Date: 2026-01-03 23:42:34.303038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08318967186'
down_revision: Union[str, None] = 'd9cdd04d1bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_embedding', table_name='memory_chunks', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('nodes', sa.Column('selected_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'selected_text')
    op.create_index('idx_memory_embedding', 'memory_chunks', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
