"""add model selection fields

Revision ID: ac0196b33def
Revises: ec0bc99964a9
Create Date: 2026-01-15 23:55:34.782046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0196b33def'
down_revision: Union[str, None] = 'ec0bc99964a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('default_model', sa.String(length=100), nullable=True))
    op.add_column('user_preferences', sa.Column('preferred_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'preferred_model')
    op.drop_column('sessions', 'default_model')
    # ### end Alembic commands ###
